# Generated by Django 3.2.3 on 2021-05-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_by',
            new_name='author',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='post', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
