# Generated by Django 3.2.3 on 2021-05-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210520_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fileurl',
            field=models.CharField(max_length=300),
        ),
    ]
